Fix SonarQube quality gate report path

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,7 +44,7 @@ jobs:
 
 
   # ==========================================================
-  # 2. SONARQUBE
+  # 2. SONARQUBE ANALYSIS
   # ==========================================================
 
   sonar:
@@ -70,7 +70,10 @@ jobs:
         env:
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         run: |
-          echo "Testing SonarQube connection..."
+          echo "======================================"
+          echo "TESTING SONARQUBE CONNECTION"
+          echo "======================================"
+
           echo "SonarQube URL: $SONAR_HOST_URL"
 
           curl --fail \
@@ -81,11 +84,16 @@ jobs:
           echo
           echo "SonarQube connection successful."
 
+
       - name: SonarQube Analysis
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         run: |
+          echo "======================================"
+          echo "STARTING SONARQUBE ANALYSIS"
+          echo "======================================"
+
           mvn -B clean verify \
             org.sonarsource.scanner.maven:sonar-maven-plugin:5.4.0.6343:sonar \
             -Dsonar.projectKey=releasepulse \
@@ -93,29 +101,68 @@ jobs:
             -Dsonar.host.url="$SONAR_HOST_URL" \
             -Dsonar.token="$SONAR_TOKEN"
 
+          echo
+          echo "======================================"
+          echo "SONARQUBE ANALYSIS COMPLETED"
+          echo "======================================"
+
+
       - name: Check SonarQube scanner result
         if: always()
         run: |
           echo "======================================"
-          echo "SONARQUBE SCANNER RESULT"
+          echo "CHECKING SONARQUBE REPORT"
           echo "======================================"
 
-          if [ -f ".scannerwork/report-task.txt" ]; then
-            echo "SUCCESS: report-task.txt exists."
+          echo
+          echo "Checking target/sonar..."
+
+          if [ -d "target/sonar" ]; then
+            echo "target/sonar EXISTS"
             echo
-            cat ".scannerwork/report-task.txt"
+            ls -la target/sonar
           else
-            echo "ERROR: report-task.txt is missing."
-            echo
-            echo "Searching for SonarQube files..."
-            find . -type f \
-              \( -name "report-task.txt" -o -name "*sonar*" \) \
-              -print || true
+            echo "target/sonar DOES NOT EXIST"
           fi
 
+          echo
+          echo "Checking target/sonar/report-task.txt..."
+
+          if [ -f "target/sonar/report-task.txt" ]; then
+            echo "SUCCESS: target/sonar/report-task.txt exists."
+            echo
+            cat target/sonar/report-task.txt
+          else
+            echo "ERROR: target/sonar/report-task.txt is missing."
+          fi
+
+          echo
+          echo "Checking .scannerwork..."
+
+          if [ -d ".scannerwork" ]; then
+            echo ".scannerwork EXISTS"
+            ls -la .scannerwork
+          else
+            echo ".scannerwork DOES NOT EXIST"
+          fi
+
+          echo
+          echo "======================================"
+          echo "SEARCHING FOR SONAR REPORT FILES"
+          echo "======================================"
+
+          find . -type f \
+            \( -name "report-task.txt" -o -name "*sonar*" \) \
+            -print || true
+
+
       - name: SonarQube Quality Gate
+        if: success()
         uses: SonarSource/sonarqube-quality-gate-action@v1
         timeout-minutes: 5
+        with:
+          scanMetadataReportFile: target/sonar/report-task.txt
+          pollingTimeoutSec: 300
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
@@ -150,10 +197,17 @@ jobs:
 
       - name: Verify WAR
         run: |
-          echo "Checking WAR file..."
+          echo "======================================"
+          echo "CHECKING WAR FILE"
+          echo "======================================"
+
           ls -lh target/
+
           test -f target/releasepulse.war
-          echo "WAR file found."
+
+          echo
+          echo "WAR file found successfully."
+
 
       - name: Upload WAR to Nexus
         env:
@@ -161,6 +215,10 @@ jobs:
           NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
           NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
         run: |
+          echo "======================================"
+          echo "UPLOADING WAR TO NEXUS"
+          echo "======================================"
+
           mvn -B deploy:deploy-file \
             -Dfile=target/releasepulse.war \
             -DgroupId=com.releasepulse \
@@ -171,6 +229,9 @@ jobs:
             -Durl="$NEXUS_URL" \
             -Dusername="$NEXUS_USERNAME" \
             -Dpassword="$NEXUS_PASSWORD"
+
+          echo
+          echo "WAR uploaded to Nexus successfully."
 
 
   # ==========================================================
@@ -192,10 +253,17 @@ jobs:
 
       - name: Verify WAR
         run: |
-          echo "Checking WAR file..."
+          echo "======================================"
+          echo "CHECKING WAR FILE"
+          echo "======================================"
+
           ls -lh target/
+
           test -f target/releasepulse.war
-          echo "WAR file found."
+
+          echo
+          echo "WAR file found successfully."
+
 
       - name: Deploy WAR to Tomcat
         env:
@@ -204,12 +272,18 @@ jobs:
           TOMCAT_SSH_KEY: ${{ secrets.TOMCAT_SSH_KEY }}
         run: |
 
-          echo "Preparing SSH key..."
+          echo "======================================"
+          echo "PREPARING SSH KEY"
+          echo "======================================"
 
           echo "$TOMCAT_SSH_KEY" > tomcat_key.pem
           chmod 600 tomcat_key.pem
 
-          echo "Stopping Tomcat..."
+
+          echo
+          echo "======================================"
+          echo "STOPPING TOMCAT"
+          echo "======================================"
 
           ssh \
             -o StrictHostKeyChecking=no \
@@ -217,7 +291,11 @@ jobs:
             "$TOMCAT_USER@$TOMCAT_HOST" \
             "sudo systemctl stop tomcat || true"
 
-          echo "Copying WAR to Tomcat server..."
+
+          echo
+          echo "======================================"
+          echo "COPYING WAR TO TOMCAT SERVER"
+          echo "======================================"
 
           scp \
             -o StrictHostKeyChecking=no \
@@ -225,7 +303,11 @@ jobs:
             target/releasepulse.war \
             "$TOMCAT_USER@$TOMCAT_HOST:/tmp/releasepulse.war"
 
-          echo "Installing WAR..."
+
+          echo
+          echo "======================================"
+          echo "INSTALLING WAR"
+          echo "======================================"
 
           ssh \
             -o StrictHostKeyChecking=no \
@@ -236,6 +318,16 @@ jobs:
              sudo mv /tmp/releasepulse.war /var/lib/tomcat10/webapps/releasepulse.war && \
              sudo systemctl start tomcat"
 
+
+          echo
+          echo "======================================"
+          echo "CLEANING SSH KEY"
+          echo "======================================"
+
           rm -f tomcat_key.pem
 
-          echo "Tomcat deployment completed successfully."
+
+          echo
+          echo "======================================"
+          echo "TOMCAT DEPLOYMENT COMPLETED"
+          echo "======================================"
